### ISSUE TITLE
Hash

### ISSUE THREAD

**Issue by ghost** [wajez/utils#1]
Salam,

Hashing is fun.
"sha256 is unbreakable unless computers are made of something other than matter and occupy other than space".

how do you chain your tools?

**Comment by webNeat** [comment]
Wa alaykom salam,

Sorry but I don't understand your question: "how do you chain your tools?"

Can you please clarify?

**Comment by ghost** [comment]
Salam,

how do you GIT(in terms of organizing) them for example, how do you keep track of them?
do you use every piece of software that you've ever encounter, or it is sane to build Structures around them so you can call them at a given moment? 
I'm still in the mess of loosing data every now then, that's why I asked?

How is it going though? are you still away from the country?
I hope you're doing well inchallah.

Unix Shell turned out to be the missing piece in understanding The OS after all.
but it can be broken also in terms of junky code.

Any how!
Let's keep Hacking (reading fast and not breaking things :smile: ).

Salam.

**Comment by webNeat** [comment]
Hey Abdessamad, how are you doing buddy?

Your question is a hard one, but here is what I do myself: I don't keep every software I encounter, they will just take space and become deprecated over time. I just remember useful ones and download their last version from internet when needed.
For code, it's different, I don't throw every code I write; instead I try to refactor it in a reusable way so that I can use it in multiple projects. This library is an example of refactoring some pieces of code and making them useful for everyone.

Let's keep in touch, you can enter [the chat room for this project](https://gitter.im/wajez/utils) or write me a word to my email webneat@gmail.com
